language: node_js
node_js: stable

# S: Build Lifecycle
install:
  - LIBSASS_EXT="no" npm install


before_script:
 # - npm install -g gulp

script:
  - hexo g

after_script:
  - cd ./public
  - cp ../CNAME .
  - git init
  - git config user.name "Tiany Wang"
  - git config user.email "lonelinsky@gmail.com"
  - git add .
  - git commit -m "Update Blog"
  - git push --force --quiet "https://${GITHUB_TOKEN}@${GH_REF}" master:master
# E: Build LifeCycle

branches:
  only:
    - source
env:
  global:
   - GH_REF: github.com/tiany/tiany.github.io.git
